"""Agent-first MCP 개발 환경을 설치하고 로컬 클라이언트 설정을 만든다."""

from __future__ import annotations

import argparse
import json
import platform
import shutil
import subprocess
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VENV = ROOT / ".venv"
MCP_ROOT = ROOT / "Src" / "McpServers"
ENV_FILE = ROOT / ".env"
MCP_CONFIG = ROOT / ".mcp.json"
CODEX_CONFIG = ROOT / ".codex" / "config.toml"
LOCK_FILE = ROOT / "requirements.lock"
MIN_PYTHON = (3, 12)
REQUIRED_IMPORTS = (
    "mcp",
    "PIL",
    "asyncpg",
    "httpx",
    "pytest",
    "strategic.server",
    "unity.server",
    "asset.server",
    "asset3d.server",
)
MCP_SERVERS = (
    ("research", "strategic.server"),
    ("unity", "unity.server"),
    ("asset", "asset.server"),
    ("asset3d", "asset3d.server"),
)
MCP_PROFILES = {
    "research": ("research",),
    "unity": ("unity",),
    "asset2d": ("asset",),
    "asset3d": ("asset3d",),
    "all": tuple(name for name, _module in MCP_SERVERS),
}


def venv_python() -> Path:
    return VENV / ("Scripts/python.exe" if platform.system() == "Windows" else "bin/python")


def run(*args: str) -> int:
    print("  $", " ".join(args))
    return subprocess.call(args, cwd=ROOT)


def create_environment() -> int:
    python = venv_python()
    if python.exists():
        print(f"  가상환경 유지: {python}")
        return 0
    if VENV.exists():
        print(f"  오류: 불완전한 가상환경이 있습니다: {VENV}", file=sys.stderr)
        print("  내용을 확인한 뒤 직접 제거하고 다시 실행하세요.", file=sys.stderr)
        return 1
    return run(sys.executable, "-m", "venv", str(VENV))


def install() -> int:
    python = str(venv_python())
    if not LOCK_FILE.is_file():
        print(f"Dependency lock file is missing: {LOCK_FILE}", file=sys.stderr)
        return 1
    if run(python, "-m", "pip", "install", "-r", str(LOCK_FILE)):
        return 1
    return run(
        python,
        "-m",
        "pip",
        "install",
        "--no-deps",
        "--no-build-isolation",
        "-e",
        f"{MCP_ROOT}[dev]",
    )


def seed_local_files(profile: str = "research") -> None:
    if not ENV_FILE.exists():
        shutil.copyfile(ROOT / ".env.example", ENV_FILE)
        print(f"  생성: {ENV_FILE}")
    else:
        print(f"  유지: {ENV_FILE}")

    python = str(venv_python().resolve())
    cwd = str(MCP_ROOT.resolve())
    if MCP_CONFIG.exists():
        print(f"  유지: {MCP_CONFIG}")
    else:
        servers = _mcp_servers(python, cwd, profile)
        MCP_CONFIG.write_text(
            json.dumps({"mcpServers": servers}, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )
        print(f"  생성: {MCP_CONFIG}")

    if CODEX_CONFIG.exists():
        print(f"  유지: {CODEX_CONFIG}")
    else:
        CODEX_CONFIG.parent.mkdir(parents=True, exist_ok=True)
        CODEX_CONFIG.write_text(expected_codex_config(profile), encoding="utf-8")
        print(f"  생성: {CODEX_CONFIG}")


def verify() -> int:
    python = venv_python()
    if not python.exists():
        print("  가상환경이 없습니다. --check 없이 실행하세요.", file=sys.stderr)
        return 1
    probe = (
        "import importlib, json; "
        f"names={list(REQUIRED_IMPORTS)!r}; "
        "failed={}; "
        "exec('for n in names:\\n try: importlib.import_module(n)\\n except Exception as e: failed[n]=str(e)'); "
        "print(json.dumps(failed, ensure_ascii=False))"
    )
    result = subprocess.run(
        [str(python), "-c", probe],
        cwd=MCP_ROOT,
        capture_output=True,
        text=True,
    )
    if result.returncode:
        print(result.stderr.strip(), file=sys.stderr)
        return 1
    failed = json.loads(result.stdout.strip().splitlines()[-1])
    if failed:
        for name, reason in failed.items():
            print(f"  X {name}: {reason}", file=sys.stderr)
        return 1
    print(f"  OK 필수 모듈 {len(REQUIRED_IMPORTS)}개")
    return 0


def expected_mcp_config(profile: str = "research") -> dict[str, object]:
    """Return the MCP configuration for this specific checkout."""

    python = str(venv_python().resolve())
    cwd = str(MCP_ROOT.resolve())
    return {"mcpServers": _mcp_servers(python, cwd, profile)}


def expected_codex_config(profile: str = "research") -> str:
    """Return a project-scoped Codex MCP configuration for the selected role."""

    servers = _mcp_servers(str(venv_python().resolve()), str(MCP_ROOT.resolve()), profile)
    sections = [
        "# Generated by scripts/bootstrap.py. Restart Codex after changing profiles.\n"
    ]
    for name, server in servers.items():
        sections.extend(
            [
                f"[mcp_servers.{name}]\n",
                f"command = {json.dumps(server['command'], ensure_ascii=False)}\n",
                f"args = {json.dumps(server['args'], ensure_ascii=False)}\n",
                f"cwd = {json.dumps(server['cwd'], ensure_ascii=False)}\n",
                "enabled = true\n",
                "required = true\n",
                f"\n[mcp_servers.{name}.env]\n",
                f"PYTHONPATH = {json.dumps(server['env']['PYTHONPATH'], ensure_ascii=False)}\n\n",
            ]
        )
    content = "".join(sections)
    tomllib.loads(content)
    return content


def _mcp_servers(
    python: str, cwd: str, profile: str = "research"
) -> dict[str, dict[str, object]]:
    """Build the selected role's MCP server map for creation, checking, and repair."""

    available = {
        name: {
            "command": python,
            "args": ["-m", module],
            "cwd": cwd,
            "env": {"PYTHONPATH": cwd},
        }
        for name, module in MCP_SERVERS
    }
    try:
        selected = MCP_PROFILES[profile]
    except KeyError as exc:
        raise ValueError(f"unknown MCP profile: {profile}") from exc
    return {name: available[name] for name in selected}


def mcp_config_is_current(profile: str = "research") -> bool:
    """Check a preserved local config without reading or printing any secrets."""

    try:
        current = json.loads(MCP_CONFIG.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return False
    return current == expected_mcp_config(profile) and codex_config_is_current(profile)


def codex_config_is_current(profile: str = "research") -> bool:
    try:
        current = tomllib.loads(CODEX_CONFIG.read_text(encoding="utf-8"))
        expected = tomllib.loads(expected_codex_config(profile))
    except (OSError, tomllib.TOMLDecodeError):
        return False
    return current == expected


def _replace_with_backup(path: Path, content: str) -> None:
    """Preserve the first local config, then allow repeatable role switches."""

    backup = path.with_suffix(path.suffix + ".bak")
    if path.exists():
        if backup.exists():
            print(f"MCP config backup preserved: {backup}")
        else:
            shutil.copyfile(path, backup)
            print(f"MCP config backup: {backup}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"MCP config repaired: {path}")


def repair_mcp_config(profile: str = "research") -> int:
    """Back up and recreate compatible-host and Codex configs for this checkout."""

    _replace_with_backup(
        MCP_CONFIG,
        json.dumps(expected_mcp_config(profile), ensure_ascii=False, indent=2) + "\n",
    )
    _replace_with_backup(CODEX_CONFIG, expected_codex_config(profile))
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="설치 없이 현재 상태만 검사")
    parser.add_argument(
        "--repair-mcp-config",
        action="store_true",
        help="back up and recreate .mcp.json for this checkout",
    )
    parser.add_argument(
        "--mcp-profile",
        choices=tuple(MCP_PROFILES),
        default="research",
        help="register only the MCP server needed for this role (default: research)",
    )
    args = parser.parse_args()
    if sys.version_info < MIN_PYTHON and not args.check:
        print("Python 3.12 이상이 필요합니다.", file=sys.stderr)
        return 1
    if args.check:
        return verify()
    if create_environment() or install():
        return 1
    seed_local_files(args.mcp_profile)
    if args.repair_mcp_config:
        if repair_mcp_config(args.mcp_profile):
            return 1
    elif not mcp_config_is_current(args.mcp_profile):
        print(
            "WARNING: local MCP configs do not match this checkout and profile. Existing "
            "settings were preserved. Run with --repair-mcp-config to back up and recreate them."
        )
    return verify()


if __name__ == "__main__":
    raise SystemExit(main())
